################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/common/cpu_endian.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/common/date_time.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/common/os_port_freertos.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/common/str.c 

OBJS += \
./Common_Sources/cpu_endian.o \
./Common_Sources/date_time.o \
./Common_Sources/os_port_freertos.o \
./Common_Sources/str.o 

C_DEPS += \
./Common_Sources/cpu_endian.d \
./Common_Sources/date_time.d \
./Common_Sources/os_port_freertos.d \
./Common_Sources/str.d 


# Each subdirectory must supply rules for building sources it contributes
Common_Sources/cpu_endian.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/common/cpu_endian.c Common_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Common_Sources/date_time.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/common/date_time.c Common_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Common_Sources/os_port_freertos.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/common/os_port_freertos.c Common_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Common_Sources/str.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/common/str.c Common_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Common_Sources

clean-Common_Sources:
	-$(RM) ./Common_Sources/cpu_endian.cyclo ./Common_Sources/cpu_endian.d ./Common_Sources/cpu_endian.o ./Common_Sources/cpu_endian.su ./Common_Sources/date_time.cyclo ./Common_Sources/date_time.d ./Common_Sources/date_time.o ./Common_Sources/date_time.su ./Common_Sources/os_port_freertos.cyclo ./Common_Sources/os_port_freertos.d ./Common_Sources/os_port_freertos.o ./Common_Sources/os_port_freertos.su ./Common_Sources/str.cyclo ./Common_Sources/str.d ./Common_Sources/str.o ./Common_Sources/str.su

.PHONY: clean-Common_Sources

