################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/src/debug.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/src/main.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/src/stm32f7xx_it.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/src/system_stm32f7xx.c 

OBJS += \
./Demo_Sources/debug.o \
./Demo_Sources/main.o \
./Demo_Sources/stm32f7xx_it.o \
./Demo_Sources/system_stm32f7xx.o 

C_DEPS += \
./Demo_Sources/debug.d \
./Demo_Sources/main.d \
./Demo_Sources/stm32f7xx_it.d \
./Demo_Sources/system_stm32f7xx.d 


# Each subdirectory must supply rules for building sources it contributes
Demo_Sources/debug.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/src/debug.c Demo_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Demo_Sources/main.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/src/main.c Demo_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Demo_Sources/stm32f7xx_it.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/src/stm32f7xx_it.c Demo_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Demo_Sources/system_stm32f7xx.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/src/system_stm32f7xx.c Demo_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Demo_Sources

clean-Demo_Sources:
	-$(RM) ./Demo_Sources/debug.cyclo ./Demo_Sources/debug.d ./Demo_Sources/debug.o ./Demo_Sources/debug.su ./Demo_Sources/main.cyclo ./Demo_Sources/main.d ./Demo_Sources/main.o ./Demo_Sources/main.su ./Demo_Sources/stm32f7xx_it.cyclo ./Demo_Sources/stm32f7xx_it.d ./Demo_Sources/stm32f7xx_it.o ./Demo_Sources/stm32f7xx_it.su ./Demo_Sources/system_stm32f7xx.cyclo ./Demo_Sources/system_stm32f7xx.d ./Demo_Sources/system_stm32f7xx.o ./Demo_Sources/system_stm32f7xx.su

.PHONY: clean-Demo_Sources

