################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/croutine.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/portable/memmang/heap_3.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/list.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/portable/gcc/arm_cm7/r0p1/port.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/queue.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/tasks.c \
G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/timers.c 

OBJS += \
./FreeRTOS_Sources/croutine.o \
./FreeRTOS_Sources/heap_3.o \
./FreeRTOS_Sources/list.o \
./FreeRTOS_Sources/port.o \
./FreeRTOS_Sources/queue.o \
./FreeRTOS_Sources/tasks.o \
./FreeRTOS_Sources/timers.o 

C_DEPS += \
./FreeRTOS_Sources/croutine.d \
./FreeRTOS_Sources/heap_3.d \
./FreeRTOS_Sources/list.d \
./FreeRTOS_Sources/port.d \
./FreeRTOS_Sources/queue.d \
./FreeRTOS_Sources/tasks.d \
./FreeRTOS_Sources/timers.d 


# Each subdirectory must supply rules for building sources it contributes
FreeRTOS_Sources/croutine.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/croutine.c FreeRTOS_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
FreeRTOS_Sources/heap_3.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/portable/memmang/heap_3.c FreeRTOS_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
FreeRTOS_Sources/list.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/list.c FreeRTOS_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
FreeRTOS_Sources/port.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/portable/gcc/arm_cm7/r0p1/port.c FreeRTOS_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
FreeRTOS_Sources/queue.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/queue.c FreeRTOS_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
FreeRTOS_Sources/tasks.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/tasks.c FreeRTOS_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
FreeRTOS_Sources/timers.o: G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/third_party/freertos/timers.c FreeRTOS_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F767xx -DUSE_HAL_DRIVER -DUSE_STM32F7XX_NUCLEO_144 -D_WINSOCK_H -c -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../src" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/cmsis/core/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f7xx" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f7xx_hal_driver/inc" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f7xx_nucleo_144" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm7/r0p1" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../common" -I"G:/WorkSpace/STM32/STM32_CYCLONETCP_EXAMPLES/CycloneTCP_SSL_SSH_IPSEC_EAP_CRYPTO_Open_2_5_2/demo/st/nucleo_f767zi/ftp_client_demo/stm32_cube_ide/../../../../../cyclone_tcp" -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-FreeRTOS_Sources

clean-FreeRTOS_Sources:
	-$(RM) ./FreeRTOS_Sources/croutine.cyclo ./FreeRTOS_Sources/croutine.d ./FreeRTOS_Sources/croutine.o ./FreeRTOS_Sources/croutine.su ./FreeRTOS_Sources/heap_3.cyclo ./FreeRTOS_Sources/heap_3.d ./FreeRTOS_Sources/heap_3.o ./FreeRTOS_Sources/heap_3.su ./FreeRTOS_Sources/list.cyclo ./FreeRTOS_Sources/list.d ./FreeRTOS_Sources/list.o ./FreeRTOS_Sources/list.su ./FreeRTOS_Sources/port.cyclo ./FreeRTOS_Sources/port.d ./FreeRTOS_Sources/port.o ./FreeRTOS_Sources/port.su ./FreeRTOS_Sources/queue.cyclo ./FreeRTOS_Sources/queue.d ./FreeRTOS_Sources/queue.o ./FreeRTOS_Sources/queue.su ./FreeRTOS_Sources/tasks.cyclo ./FreeRTOS_Sources/tasks.d ./FreeRTOS_Sources/tasks.o ./FreeRTOS_Sources/tasks.su ./FreeRTOS_Sources/timers.cyclo ./FreeRTOS_Sources/timers.d ./FreeRTOS_Sources/timers.o ./FreeRTOS_Sources/timers.su

.PHONY: clean-FreeRTOS_Sources

